name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push service-a Docker image
        run: |
          docker build -t joshuamsaechao/service-a ./src/service-a
          docker push joshuamsaechao/service-a

      - name: Build and push service-b Docker image
        run: |
          docker build -t joshuamsaechao/service-b ./src/service-b
          docker push joshuamsaechao/service-b

      - name: Build and push frontend Docker image
        run: |
          docker build -t joshuamsaechao/service-c ./src/service-c
          docker push joshuamsaechao/service-c

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          #kubectl apply -f k8s/istio/istio-installation.yaml
          kubectl apply -f manifests/app/service-a-deployment.yaml -n microservices
          kubectl apply -f manifests/app/service-b-service.yaml -n microservices
          
          kubectl apply -f manifests/app/service-b-deployment.yaml -n microservices
          kubectl apply -f manifests/app/service-b-service.yaml -n microservices
          
          kubectl apply -f manifests/app/service-c-deployment.yaml -n microservices
          kubectl apply -f manifests/app/service-c-service.yaml -n microservices
          
          kubectl apply -f manifests/mesh/service-a-destinationrule.yaml -n microservices
          kubectl apply -f manifests/mesh/service-a-virtualservice.yaml -n microservices
          
          kubectl apply -f manifests/mesh/service-b-destinationrule.yaml -n microservices
          kubectl apply -f manifests/mesh/service-b-virtualservice.yaml -n microservices
          
          kubectl apply -f manifests/mesh/service-c-destinationrule.yaml -n microservices
          kubectl apply -f manifests/mesh/service-c-virtualservice.yaml -n microservices
